#!/bin/bash

if [ $# -eq 0 ]
    then
        echo "Usage: script/run {file.mp3} {live|offline}"
    else
        echo "Running Robot Drops in "$2" mode..."
        bundle exec ruby src/analyzer.rb $1 $2
        bundle exec ruby src/robotdrops.rb
fi
